const Order = require('./models/order'); // Assuming you have a User model defined
const bodyParser = require('body-parser');
const urlencoderParser = bodyParser.urlencoded({ extended: false });
const connection = require('./database');

async function handleOrderStoring(req, res) {
  console.log('********* Request body:', req.body);
  const { user_id, shipping_address, payment_method, items, total_amount, order_status } = req.body;
  try {
    const order = new Order({
      user_id,
      shipping_address,
      payment_method,
      items,
      total_amount,
      order_status
    });

    console.log('Order before saving:', order._doc);  // Log the order object before saving
    await order.save();
    console.log(' order information stored:', order);
    console.log('Order saved successfully');  // Confirm order saved
    res.status(200).json({
      order: {
          id: order._id,  // Assuming _id is generated by MongoDB
          status: order.order_status,
          totalAmount: order.total_Amount,
          items: order.items.map(item => ({
              product_id: item.id,
              product_name: item.product_name,
              price: item.price,
              quantity: item.quantity
          }))
      }
  });


  } catch (error) {
    res.status(500).json({ message: 'Failed to create order', error: error });
  }
}

module.exports = { handleOrderStoring };