// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQ8JL_MGVA2SoXlpy1pOhs-E8k8wJKjs',
    appId: '1:9155793675:web:4ae867ecae4fe113ea480e',
    messagingSenderId: '9155793675',
    projectId: 'gradprojfb',
    authDomain: 'gradprojfb.firebaseapp.com',
    storageBucket: 'gradprojfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9trlC6b4uc4mqjHIjHYwJqmI5vvo21I4',
    appId: '1:9155793675:android:8c3244e683881c8aea480e',
    messagingSenderId: '9155793675',
    projectId: 'gradprojfb',
    storageBucket: 'gradprojfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF88JuFEHCS3Z2mjtUQ0rCzZaOkH1UYyg',
    appId: '1:9155793675:ios:8b9a61059b56e4a2ea480e',
    messagingSenderId: '9155793675',
    projectId: 'gradprojfb',
    storageBucket: 'gradprojfb.appspot.com',
    iosBundleId: 'com.example.project1',
  );
}
